### ISSUE TITLE
Installation with bundler fails

### ISSUE THREAD

**Issue by depili** [marvindanig/threejs-rails#2]
Fetching https://github.com/marvindanig/threejs-rails/
The gemspec at .../.rvm/gems/ruby-2.4.1/bundler/gems/threejs-rails-ac5c237dfd27/threejs-rails.gemspec is not valid. Please fix this gemspec.
The validation error was 'threejs-rails-1.1.3 contains itself (threejs-rails-1.1.3.gem), check your files list'

The problem is commit ac5c237dfd2766bd005b746f81dc5c515ce07d08 which added the .gem file to the repository and thus the file list in the gemspec will now include the gem itself. b77626bea6089910721d59d75a5b7e7e949e8b72 is working fine.

**Comment by marvindanig** [comment]
#[2](https://github.com/marvindanig/threejs-rails/commit/5e046f4f4cf9194c0784c918c5052b1b29b65afa)  fixed.
