### ISSUE TITLE
three.js file is trunkated

### ISSUE THREAD

**Issue by depili** [marvindanig/threejs-rails#3]
The non-minified version of three.js has been cut off as can be seen in https://github.com/marvindanig/threejs-rails/blob/master/vendor/assets/javascripts/three.js#L29558 which also features a unterminated comment and thus the file is completely useless.

**Comment by marvindanig** [comment]
#[3](https://github.com/marvindanig/threejs-rails/commit/7560ea52c6c8483d1ad176faf17ba2cef0015f0d) Resolved.

**Comment by marvindanig** [comment]
I remember not being able to publish this gem to rubygems earlier for some reason. Will come back to this in a week.
