### ISSUE TITLE
Is this gem published?

### ISSUE THREAD

**Issue by rodrigovrm** [marvindanig/threejs-rails#6]
Hi, 

I just checked rubygems website and the gem named `threejs-rails` isn't this one: http://rubygems.org/gems/threejs-rails 

Am I missing something?

**Comment by marvindanig** [comment]
The name is squatted on rubygems, I think, wrote an email to its owner but did not hear.  Right now not enough time to pursue the issue with rg.

**Comment by rodrigovrm** [comment]
Yea ok.

Thank you!
